---
- name: Install Apache HTTP Server and PHP
  hosts: all
  become: true

  tasks:
    - name: Install apache and php packages
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present

    - name: Start and enable apache service
      systemd:
        name: "{{ apache_package }}"
        state: started
        enabled: yes



